export { HeroSection } from "./HeroSection";
export { PropuestaSection } from "./PropuestaSection";
export { ComoFuncionaSection } from "./ComoFuncionaSection";
export { AgendaSection } from "./AgendaSection";
export { TestimoniosSection } from "./TestimoniosSection";
export { SobreTriniSection } from "./SobreTriniSection";
export { CtaSection } from "./CtaSection";
export { DisciplinesSection } from "./DisciplinesSection";
export { ContactSection } from "./ContactSection";
export { LibrarySection } from "./LibrarySection";
export { EventsSection, type UpcomingEvent } from "./EventsSection";
export { FaqSection, type FaqItem } from "./FaqSection";
export { GallerySection } from "./GallerySection";
export { PlaylistSection } from "./PlaylistSection";
export { NewsletterSection } from "./NewsletterSection";
